CREATE TABLE `Cards` (
  `UID`     VARCHAR(10)  NOT NULL UNIQUE,
  `Enabled` BOOLEAN      NOT NULL DEFAULT FALSE,
  `Changed` DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `Created` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UserREF` VARCHAR(255) NULL,
  PRIMARY KEY (`UID`),
  CONSTRAINT Card_User
  FOREIGN KEY (UserREF) REFERENCES Users (Username)
    ON DELETE SET NULL
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;