CREATE TABLE `TransactionMarks` (
  `ID`          INT UNSIGNED NOT NULL         AUTO_INCREMENT,
  `Date`        DATETIME     NOT NULL         DEFAULT CURRENT_TIMESTAMP,
  `TREF`        INT UNSIGNED NOT NULL UNIQUE,
  `Solved`      BOOLEAN      NOT NULL         DEFAULT FALSE,
  `Changed` DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  CONSTRAINT TMark_Trans
  FOREIGN KEY (TREF) REFERENCES Transactions (ID)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;



